### PR TITLE
CI: add MacOSX builds

### PR DESCRIPTION
**Pull request by erickwilder**
In order to guarantee the correct behaviour of the library on all platforms
we need to ensure that both Linux and MacOSX builds are OK

### CODE REVIEW

**Comment by osantana** [comment]
Tem alguma coisa quebrando lá no Travis...

**Comment by erickwilder** [comment]
That's because Mac OSX builds are a beta feature of Travis. I asked the
team to enable on this repo. I'm waiting their response.

Erick Wilder
http://erickwilder.com
erickwilder@gmail.com
+55 11 994438 000

**Comment by osantana** [comment]
Oh! Ok.

Is it ok to merge even with this warning or it's better to wait?

**Comment by erickwilder** [comment]
Is better to wait.

**Comment by erickwilder** [comment]
@osantana, @bertonha 
We're green! Can we merge?

**Comment by osantana** [comment]
fiz release... já tá no PyPI

**Comment by erickwilder** [comment]
Nice!

**Pull request merged**
